version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: message_service
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_KRAFT_MODE: "true"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CFG_LOG_RETENTION_MS: "604800000" # 7 дней
      KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824" # 1гб
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./data/kafka:/var/lib/kafka:rw

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://username:password@db:5432/message_service?sslmode=disable"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - db
      - kafka

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./auth_basic:/etc/nginx/auth_basic
    depends_on:
      - app

